allowBuilds:
  '@firebase/util': true
  '@sentry/cli': true
  protobufjs: true
  sharp: true
minimumReleaseAgeExclude:
  - '@sentry/browser-utils@10.65.0'
  - '@sentry/browser@10.65.0'
  - '@sentry/core@10.65.0'
  - '@sentry/feedback@10.65.0'
  - '@sentry/nextjs@10.65.0'
  - '@sentry/node-core@10.65.0'
  - '@sentry/node@10.65.0'
  - '@sentry/opentelemetry@10.65.0'
  - '@sentry/react@10.65.0'
  - '@sentry/replay-canvas@10.65.0'
  - '@sentry/replay@10.65.0'
  - '@sentry/server-utils@10.65.0'
  - '@sentry/vercel-edge@10.65.0'
