import type {
	FormationDefinition,
	FormationKey,
	PitchThemeConfig,
	PitchTheme,
} from "./types";

export const FORMATIONS: Record<FormationKey, FormationDefinition> = {
	"4-3-3": {
		id: "4-3-3",
		name: "4-3-3 Standard",
		description:
			"Balanced possession system with wide wingers and a single holding anchor.",
		category: "Attacking",
		slots: [
			{
				id: "slot-gk",
				role: "GK",
				label: "GK",
				x: 50,
				y: 90,
				defaultNumber: 1,
			},
			{
				id: "slot-lb",
				role: "DF",
				label: "LB",
				x: 16,
				y: 72,
				defaultNumber: 3,
			},
			{
				id: "slot-lcb",
				role: "DF",
				label: "CB",
				x: 38,
				y: 74,
				defaultNumber: 4,
			},
			{
				id: "slot-rcb",
				role: "DF",
				label: "CB",
				x: 62,
				y: 74,
				defaultNumber: 5,
			},
			{
				id: "slot-rb",
				role: "DF",
				label: "RB",
				x: 84,
				y: 72,
				defaultNumber: 2,
			},
			{
				id: "slot-cdm",
				role: "MF",
				label: "CDM",
				x: 50,
				y: 56,
				defaultNumber: 6,
			},
			{
				id: "slot-lcm",
				role: "MF",
				label: "CM",
				x: 32,
				y: 44,
				defaultNumber: 8,
			},
			{
				id: "slot-rcm",
				role: "MF",
				label: "CM",
				x: 68,
				y: 44,
				defaultNumber: 10,
			},
			{
				id: "slot-lw",
				role: "FW",
				label: "LW",
				x: 18,
				y: 22,
				defaultNumber: 11,
			},
			{
				id: "slot-st",
				role: "FW",
				label: "ST",
				x: 50,
				y: 16,
				defaultNumber: 9,
			},
			{
				id: "slot-rw",
				role: "FW",
				label: "RW",
				x: 82,
				y: 22,
				defaultNumber: 7,
			},
		],
	},
	"4-2-3-1": {
		id: "4-2-3-1",
		name: "4-2-3-1 Modern",
		description:
			"Double pivot stability with a creative playmaker and attacking wide threats.",
		category: "Balanced",
		slots: [
			{
				id: "slot-gk",
				role: "GK",
				label: "GK",
				x: 50,
				y: 90,
				defaultNumber: 1,
			},
			{
				id: "slot-lb",
				role: "DF",
				label: "LB",
				x: 16,
				y: 72,
				defaultNumber: 3,
			},
			{
				id: "slot-lcb",
				role: "DF",
				label: "CB",
				x: 38,
				y: 74,
				defaultNumber: 4,
			},
			{
				id: "slot-rcb",
				role: "DF",
				label: "CB",
				x: 62,
				y: 74,
				defaultNumber: 5,
			},
			{
				id: "slot-rb",
				role: "DF",
				label: "RB",
				x: 84,
				y: 72,
				defaultNumber: 2,
			},
			{
				id: "slot-ldm",
				role: "MF",
				label: "CDM",
				x: 36,
				y: 58,
				defaultNumber: 6,
			},
			{
				id: "slot-rdm",
				role: "MF",
				label: "CDM",
				x: 64,
				y: 58,
				defaultNumber: 8,
			},
			{
				id: "slot-cam",
				role: "MF",
				label: "CAM",
				x: 50,
				y: 38,
				defaultNumber: 10,
			},
			{
				id: "slot-lm",
				role: "FW",
				label: "LM",
				x: 18,
				y: 32,
				defaultNumber: 11,
			},
			{
				id: "slot-rm",
				role: "FW",
				label: "RM",
				x: 82,
				y: 32,
				defaultNumber: 7,
			},
			{
				id: "slot-st",
				role: "FW",
				label: "ST",
				x: 50,
				y: 16,
				defaultNumber: 9,
			},
		],
	},
	"4-4-2": {
		id: "4-4-2",
		name: "4-4-2 Classic",
		description:
			"Two banks of four with dual strikers for disciplined pressing and direct transitions.",
		category: "Balanced",
		slots: [
			{
				id: "slot-gk",
				role: "GK",
				label: "GK",
				x: 50,
				y: 90,
				defaultNumber: 1,
			},
			{
				id: "slot-lb",
				role: "DF",
				label: "LB",
				x: 16,
				y: 72,
				defaultNumber: 3,
			},
			{
				id: "slot-lcb",
				role: "DF",
				label: "CB",
				x: 38,
				y: 74,
				defaultNumber: 4,
			},
			{
				id: "slot-rcb",
				role: "DF",
				label: "CB",
				x: 62,
				y: 74,
				defaultNumber: 5,
			},
			{
				id: "slot-rb",
				role: "DF",
				label: "RB",
				x: 84,
				y: 72,
				defaultNumber: 2,
			},
			{
				id: "slot-lm",
				role: "MF",
				label: "LM",
				x: 16,
				y: 46,
				defaultNumber: 11,
			},
			{
				id: "slot-lcm",
				role: "MF",
				label: "CM",
				x: 38,
				y: 48,
				defaultNumber: 6,
			},
			{
				id: "slot-rcm",
				role: "MF",
				label: "CM",
				x: 62,
				y: 48,
				defaultNumber: 8,
			},
			{
				id: "slot-rm",
				role: "MF",
				label: "RM",
				x: 84,
				y: 46,
				defaultNumber: 7,
			},
			{
				id: "slot-ls",
				role: "FW",
				label: "ST",
				x: 36,
				y: 18,
				defaultNumber: 9,
			},
			{
				id: "slot-rs",
				role: "FW",
				label: "ST",
				x: 64,
				y: 18,
				defaultNumber: 10,
			},
		],
	},
	"3-5-2": {
		id: "3-5-2",
		name: "3-5-2 Wing-Back Dominance",
		description:
			"Three central defenders, high-flying wing-backs, and midfield numerical superiority.",
		category: "Balanced",
		slots: [
			{
				id: "slot-gk",
				role: "GK",
				label: "GK",
				x: 50,
				y: 90,
				defaultNumber: 1,
			},
			{
				id: "slot-lcb",
				role: "DF",
				label: "CB",
				x: 26,
				y: 73,
				defaultNumber: 3,
			},
			{
				id: "slot-cb",
				role: "DF",
				label: "CB",
				x: 50,
				y: 76,
				defaultNumber: 4,
			},
			{
				id: "slot-rcb",
				role: "DF",
				label: "CB",
				x: 74,
				y: 73,
				defaultNumber: 5,
			},
			{
				id: "slot-lwb",
				role: "MF",
				label: "LWB",
				x: 14,
				y: 50,
				defaultNumber: 11,
			},
			{
				id: "slot-cdm",
				role: "MF",
				label: "CDM",
				x: 50,
				y: 58,
				defaultNumber: 6,
			},
			{
				id: "slot-lcm",
				role: "MF",
				label: "CM",
				x: 34,
				y: 44,
				defaultNumber: 8,
			},
			{
				id: "slot-rcm",
				role: "MF",
				label: "CM",
				x: 66,
				y: 44,
				defaultNumber: 10,
			},
			{
				id: "slot-rwb",
				role: "MF",
				label: "RWB",
				x: 86,
				y: 50,
				defaultNumber: 2,
			},
			{
				id: "slot-ls",
				role: "FW",
				label: "ST",
				x: 36,
				y: 18,
				defaultNumber: 9,
			},
			{
				id: "slot-rs",
				role: "FW",
				label: "ST",
				x: 64,
				y: 18,
				defaultNumber: 7,
			},
		],
	},
	"3-4-3": {
		id: "3-4-3",
		name: "3-4-3 Total Attack",
		description:
			"High-voltage attacking trident backed by dynamic box-to-box midfield engine.",
		category: "Attacking",
		slots: [
			{
				id: "slot-gk",
				role: "GK",
				label: "GK",
				x: 50,
				y: 90,
				defaultNumber: 1,
			},
			{
				id: "slot-lcb",
				role: "DF",
				label: "CB",
				x: 26,
				y: 73,
				defaultNumber: 3,
			},
			{
				id: "slot-cb",
				role: "DF",
				label: "CB",
				x: 50,
				y: 76,
				defaultNumber: 4,
			},
			{
				id: "slot-rcb",
				role: "DF",
				label: "CB",
				x: 74,
				y: 73,
				defaultNumber: 5,
			},
			{
				id: "slot-lm",
				role: "MF",
				label: "LM",
				x: 16,
				y: 48,
				defaultNumber: 11,
			},
			{
				id: "slot-lcm",
				role: "MF",
				label: "CM",
				x: 38,
				y: 50,
				defaultNumber: 6,
			},
			{
				id: "slot-rcm",
				role: "MF",
				label: "CM",
				x: 62,
				y: 50,
				defaultNumber: 8,
			},
			{
				id: "slot-rm",
				role: "MF",
				label: "RM",
				x: 84,
				y: 48,
				defaultNumber: 2,
			},
			{
				id: "slot-lw",
				role: "FW",
				label: "LW",
				x: 20,
				y: 22,
				defaultNumber: 7,
			},
			{
				id: "slot-st",
				role: "FW",
				label: "ST",
				x: 50,
				y: 16,
				defaultNumber: 9,
			},
			{
				id: "slot-rw",
				role: "FW",
				label: "RW",
				x: 80,
				y: 22,
				defaultNumber: 10,
			},
		],
	},
	"5-3-2": {
		id: "5-3-2",
		name: "5-3-2 Solid Wall",
		description:
			"Maximum defensive solidity with rapid counter-attacks through forward duos.",
		category: "Defensive",
		slots: [
			{
				id: "slot-gk",
				role: "GK",
				label: "GK",
				x: 50,
				y: 90,
				defaultNumber: 1,
			},
			{
				id: "slot-lwb",
				role: "DF",
				label: "LWB",
				x: 14,
				y: 68,
				defaultNumber: 3,
			},
			{
				id: "slot-lcb",
				role: "DF",
				label: "CB",
				x: 32,
				y: 74,
				defaultNumber: 4,
			},
			{
				id: "slot-cb",
				role: "DF",
				label: "CB",
				x: 50,
				y: 76,
				defaultNumber: 5,
			},
			{
				id: "slot-rcb",
				role: "DF",
				label: "CB",
				x: 68,
				y: 74,
				defaultNumber: 6,
			},
			{
				id: "slot-rwb",
				role: "DF",
				label: "RWB",
				x: 86,
				y: 68,
				defaultNumber: 2,
			},
			{
				id: "slot-lcm",
				role: "MF",
				label: "CM",
				x: 32,
				y: 46,
				defaultNumber: 8,
			},
			{
				id: "slot-cdm",
				role: "MF",
				label: "CDM",
				x: 50,
				y: 54,
				defaultNumber: 16,
			},
			{
				id: "slot-rcm",
				role: "MF",
				label: "CM",
				x: 68,
				y: 46,
				defaultNumber: 10,
			},
			{
				id: "slot-ls",
				role: "FW",
				label: "ST",
				x: 36,
				y: 18,
				defaultNumber: 9,
			},
			{
				id: "slot-rs",
				role: "FW",
				label: "ST",
				x: 64,
				y: 18,
				defaultNumber: 7,
			},
		],
	},
	"4-1-2-1-2": {
		id: "4-1-2-1-2",
		name: "4-1-2-1-2 Narrow Diamond",
		description:
			"Central overload with deep playmaker, central runners, and attacking No. 10.",
		category: "Balanced",
		slots: [
			{
				id: "slot-gk",
				role: "GK",
				label: "GK",
				x: 50,
				y: 90,
				defaultNumber: 1,
			},
			{
				id: "slot-lb",
				role: "DF",
				label: "LB",
				x: 16,
				y: 72,
				defaultNumber: 3,
			},
			{
				id: "slot-lcb",
				role: "DF",
				label: "CB",
				x: 38,
				y: 74,
				defaultNumber: 4,
			},
			{
				id: "slot-rcb",
				role: "DF",
				label: "CB",
				x: 62,
				y: 74,
				defaultNumber: 5,
			},
			{
				id: "slot-rb",
				role: "DF",
				label: "RB",
				x: 84,
				y: 72,
				defaultNumber: 2,
			},
			{
				id: "slot-cdm",
				role: "MF",
				label: "CDM",
				x: 50,
				y: 58,
				defaultNumber: 6,
			},
			{
				id: "slot-lcm",
				role: "MF",
				label: "CM",
				x: 30,
				y: 46,
				defaultNumber: 8,
			},
			{
				id: "slot-rcm",
				role: "MF",
				label: "CM",
				x: 70,
				y: 46,
				defaultNumber: 7,
			},
			{
				id: "slot-cam",
				role: "MF",
				label: "CAM",
				x: 50,
				y: 34,
				defaultNumber: 10,
			},
			{
				id: "slot-ls",
				role: "FW",
				label: "ST",
				x: 36,
				y: 18,
				defaultNumber: 9,
			},
			{
				id: "slot-rs",
				role: "FW",
				label: "ST",
				x: 64,
				y: 18,
				defaultNumber: 11,
			},
		],
	},
};

export const PITCH_THEMES: Record<PitchTheme, PitchThemeConfig> = {
	"classic-emerald": {
		id: "classic-emerald",
		name: "Classic Emerald",
		bgClass: "bg-emerald-900 border-emerald-800",
		borderLineColor: "rgba(255, 255, 255, 0.65)",
		stripeColor: "rgba(16, 185, 129, 0.08)",
		nodeGlow: "shadow-emerald-900/40",
	},
	"night-floodlight": {
		id: "night-floodlight",
		name: "Night Floodlight",
		bgClass: "bg-slate-900 border-slate-800",
		borderLineColor: "rgba(148, 163, 184, 0.45)",
		stripeColor: "rgba(30, 41, 59, 0.4)",
		nodeGlow: "shadow-slate-950/60",
	},
	"tactical-slate": {
		id: "tactical-slate",
		name: "Tactical Blueprint",
		bgClass: "bg-sky-950 border-sky-900",
		borderLineColor: "rgba(56, 189, 248, 0.4)",
		stripeColor: "rgba(14, 116, 144, 0.12)",
		nodeGlow: "shadow-sky-950/50",
	},
	chalkboard: {
		id: "chalkboard",
		name: "Chalkboard",
		bgClass: "bg-stone-900 border-stone-800",
		borderLineColor: "rgba(226, 232, 240, 0.45)",
		stripeColor: "rgba(68, 64, 60, 0.15)",
		nodeGlow: "shadow-stone-950/60",
	},
};
